# Generated by Django 4.2.30 on 2026-05-26 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Companies",
                "db_table": "companies",
            },
        ),
        migrations.CreateModel(
            name="DataSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("SAP", "SAP Fuel & Procurement"),
                            ("UTILITY", "Utility Electricity Data"),
                            ("TRAVEL", "Corporate Travel Data"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_sources",
                        to="emissions.company",
                    ),
                ),
            ],
            options={
                "db_table": "data_sources",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="EmissionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("Scope 1", "Scope 1"),
                            ("Scope 2", "Scope 2"),
                            ("Scope 3", "Scope 3"),
                        ],
                        max_length=10,
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                ("activity_type", models.CharField(max_length=150)),
                ("raw_value", models.DecimalField(decimal_places=4, max_digits=18)),
                ("raw_unit", models.CharField(max_length=50)),
                (
                    "normalized_value",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                ("normalized_unit", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Pending",
                        max_length=15,
                    ),
                ),
                ("is_suspicious", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emission_records",
                        to="emissions.company",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emission_records",
                        to="emissions.datasource",
                    ),
                ),
            ],
            options={
                "db_table": "emission_records",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("Created", "Created"),
                            ("Updated", "Updated"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                        ],
                        max_length=15,
                    ),
                ),
                ("old_value", models.TextField(blank=True, null=True)),
                ("new_value", models.TextField(blank=True, null=True)),
                ("performed_by", models.CharField(default="System", max_length=150)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="emissions.emissionrecord",
                    ),
                ),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ["-timestamp"],
            },
        ),
    ]
